version: "3"
services:
     Ruleta_App1:
         container_name: Ruleta_App_1_Conte
         build: .
         image: ruleta_cleancode_api
         depends_on:        
                - db
         ports:
             - "8081:4000"
    
     db:       
         container_name: sqlserver
         build: database
         image: ruleta_cleancode_db
         ports:
              - "3000:1433"
         volumes:
            - .sqlvolume:/var/opt/mssql

     Ruleta_App2:
         container_name: Ruleta_App_2_Conte
         build: .
         image: ruleta_cleancode_api
         depends_on:        
                - db
         ports:
             - "8080:4000"
             
     nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - Ruleta_App1
            - Ruleta_App2
        ports:     
            - "8082:80"